package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    DESCONOCIDO, ENTERO, DECIMAL, IDENTIFICADOR, CADENA, CARACTER, COMENTARIO_LINEA,COMENTARIO_BLOQUE, PARENTESIS_IZQ, PARENTESIS_DER, LLAVE_IZQ, LLAVE_DER, CORCHETE_IZQ, CORCHETE_DER, PUNTO, COMA, DOS_PUNTOS, OPERADOR_ARITMETICO, OPERADOR_LOGICO, FINAL
}