package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    DESCONOCIDO, ENTERO, DECIMAL, IDENTIFICADOR, CADENA, CARACTER, COMENTARIO_LINEA,COMENTARIO_BLOQUE, PARENTESIS_IZQ, PARENTESIS_DER, LLAVE_IZQ, LLAVE_DER, CORCHETE_IZQ, CORCHETE_DER, PUNTO, COMA, DOS_PUNTOS, OPERADOR_ARITMETICO_SUMA, OPERADOR_ARITMETICO_RESTA,OPERADOR_ARITMETICO_DIVISION,OPERADOR_ARITMETICO_MULTIPLICACION, OPERADOR_LOGICO_IGUAL,
    OPERADOR_LOGICO_MENOR,OPERADOR_LOGICO_MAYOR,OPERADOR_LOGICO_Y,OPERADOR_LOGICO_O,OPERADOR_LOGICO_MAYOR_IGUAL,OPERADOR_LOGICO_MENOR_IGUAL,FINAL,PALABRA_RESERVADA_VARIABLE,PALABRA_RESERVADA_METODO,PALABRA_RESERVADA_CLASE
}